openapi: 3.0.0
servers:
  - url: https://api.reworkly.com
    description: Production
  - url: http://localhost:8080
    description: Local Development
info:
  title: Reworkly APIs
  version: v1
  termsOfService: "https://developer.reworkly.com/legal/"
  contact:
    name: Support
    email: team@reworkly.com
    url: https://github.com/reworkly
  x-logo:
    url: "https://github.com/reworkly.png"
    altText: Reworkly logo
  description: |
    # Introduction
    Use Reworkly APIs to make calls and get the data you need to integrate your application with our platform.

    **Endpoints:**

    - [Account](#tag/account-overview)
    - [Recruiting](#tag/recruiting-overview)
    - [Onboarding](#tag/onboarding-overview)
    - [Employees](#tag/employees-overview)
    - [Time and Scheduling](#tag/time-overview)
    - [Payroll](#tag/payroll-overview)

    haha:
      
    - [Server](#tag/server-overview)
    - [List of Values (LOV)](#tag/lov-overview)
    - [Profile](#tag/profile-overview)

    # Getting Started
    The Reworkly APIs are organized around REST. Our API has predictable resource-oriented URLs, 
    accepts form-encoded or JSON-encoded request bodies, returns JSON-encoded responses, 
    and uses standard HTTP response codes, authentication, and verbs.

    [See more](/docs/getting-started/)

x-tagGroups:
  - name: account
    x-displayName: Account
    tags:
      - account-overview
      # - account-datamodel
      - account-endpoints
  - name: recruiting
    x-displayName: Recruiting
    tags:
      - recruiting-overview
      - recruiting-datamodel
      - recruiting-endpoints
      - Jobs
      - Job Members
      - Job Stages
      - Job Sources
      - Job Candidates
      - Job Offers
      - Job Offer Variables
      - Job Offer Documents
      - Job Events
      - Job Event Organizers
      - Job Event Candidates
      - Pools
      - Pool Members
      - Pool Candidates
      - Sortings
      - Sorting Conditions
      - Sorting Associations
      - Sorting Association Candidates
  - name: onboarding
    x-displayName: Onboarding
    tags:
      - onboarding-overview
      - onboarding-datamodel
      - onboarding-endpoints
  - name: employees
    x-displayName: Employees
    tags:
      - employees-overview
      - employees-datamodel
      - employees-endpoints
  - name: time
    x-displayName: Time and Scheduling
    tags:
      - time-overview
      - time-datamodel
      - time-endpoints
  - name: payroll
    x-displayName: Payroll
    tags:
      - payroll-overview
      - payroll-datamodel
      - payroll-endpoints
  - name: server
    x-displayName: Server
    tags:
      - server-health
      - server-settings
  - name: lov
    x-displayName: List of Values (LOV)
    tags:
      - lov-overview
      - lov-datamodel
      - lov-endpoints
      - lov-lookups
      - lov-lookup-values
      - lov-translations
  - name: profile
    x-displayName: Profile Management
    tags:
      - profile-overview
      - profile-datamodel
      - profile-endpoints
      - profile-profiles
      - profile-profile-names
      - profile-profile-images
      - profile-profile-emails
      - profile-profile-phones
      - profile-profile-webs
      - profile-profile-socials
      - profile-profile-addresses
      - profile-profile-educations
      - profile-profile-languages
      - profile-profile-skills
      - profile-profile-experiences
      - profile-profile-attachments
      - profile-profile-citizenships
      - profile-profile-tests
      - profile-profile-test-components
      - profile-profile-awards
      - profile-profile-contents
      - profile-profile-types
      - profile-profile-type-attributes
      - profile-content-types
      - profile-content-type-attributes
      - profile-rating-scales
      - profile-rating-scale-levels
  - name: integration
    x-displayName: Integration
    tags:
      - Integration Overview
      - Assessment
      - Background Check
      - Evaluation/Rating
tags:
  # General Tags
  - name: server-health
    x-displayName: Server Health
    description: Server Health for Reworkly APIs
  - name: server-settings
    x-displayName: Server Settings
    description: Server Settings for Reworkly APIs
  # Account
  - name: account-overview
    x-displayName: Account Overview
    description: |
      Reworkly Account
  - name: account-datamodel
    x-displayName: Account Data Model
    description: |
      The data model of the Account is represented by the following conceptual model. 
      This will make it easier for you to understand the Account Endpoints.

      <a href="/img/datamodel/reworkly_account.png" target="_blank">
        <img src="/img/datamodel/reworkly_account.png" alt="Account Data Model" />
      </a>

      _Click to enlarge the image._
  - name: account-endpoints
    x-displayName: Account Endpoints
    description: |
      ### Accounts:
      - [Accounts](#tag/Accounts)

      ### Account Settings:
  # Recruiting
  - name: recruiting-overview
    x-displayName: Recruiting Overview
    description: |
      Reworkly Recruiting optimizes enrollment and improve recruiter productivity by identifying and targeting high-value candidates.
  - name: recruiting-datamodel
    x-displayName: Recruiting Data Model
    description: |
      The data model of the Recruiting is represented by the following conceptual model. 
      This will make it easier for you to understand the Recruiting Endpoints.

      <a href="/img/datamodel/reworkly_recruit.png" target="_blank">
        <img src="/img/datamodel/reworkly_recruit.png" alt="Recruiting Data Model" />
      </a>

      _Click to enlarge the image._
  - name: recruiting-endpoints
    x-displayName: Recruiting Endpoints
    description: |
      ### Job:
      - [Jobs](#tag/Jobs)
      - [Job Members](#tag/Job-Members)
      - [Job Stages](#tag/Job-Stages)
      - [Job Sources](#tag/Job-Sources)
      - [Job Candidates](#tag/Job-Candidates)
      - [Job Offers](#tag/Job-Offers)
      - [Job Offer Variables](#tag/Job-Offer-Variables)
      - [Job Offer Documents](#tag/Job-Offer-Documents)
      - [Job Events](#tag/Job-Events)
      - [Job Event Organizers](#tag/Job-Event-Organizers)
      - [Job Event Candidates](#tag/Job-Event-Candidates)

      ### Talent Pool:
      - [Pools](#tag/Pools)
      - [Pool Members](#tag/Pool-Members)
      - [Pool Candidates](#tag/Pool-Candidates)

      ### Candidate Sorting:
      - [Sortings](#tag/Sortings)
      - [Sorting Conditions](#tag/Sorting-Conditions)
      - [Sorting Associations](#tag/Sorting-Associations)
      - [Sorting Association Candidates](#tag/Sorting-Association-Candidates)
  - name: Jobs
    x-displayName: Jobs
    description: |
      You create jobs that contain the specific requirements for a job for which candidates are hired. 
      A job can contain prescreening questionnaires and screening services such as background checks. 
      You post jobs on the career site that candidates visit as they search for jobs to apply for or refer people for the job.
  - name: Job Members
    x-displayName: Job Members
    description: |
      Admins on your account have access to every job and candidate, 
      but do not need to be included in the team member if the job is not relevant to them. 

      They can add or remove themselves from the team member of the job at any time.

      Other members must be added to the job's member to have access to candidates and assist with the recruiting process. 
      If they are not on the job members they will not be able to see or interact with candidates for that job.
  - name: Job Stages
    description: |
      Job Stage is a recruiting pipeline that can be used to create different recruiting processes for different types of jobs.

      Available Types:
        - Sourced
        - Applied
        - Shortlisted
        - Assessment
        - Interview
        - Offer
        - Hired
  - name: Job Sources
    description: |
      Job Source identifies the source from which the applicant is registered.

      Source Types:
        - **Manual** - Used only if a recruiter add a candidate manually.
        - **Career Page** - Used only if a candidate apply from the Career Page.
  - name: Job Candidates
    description: |
      Candidates.
  - name: Job Offers
    description: |
      Job Offers.
  - name: Job Events
    description: |
      Job Event is a calendar event such as a call, an interview, and a meeting. 

      Event Types:
        - Call
        - Interview
        - Meeting
  - name: Job Event Organizers
    description: |
      An Event Organizer is the member participating in the event. Each organizer object contains the id, the member id, the data of the member and the status.
  - name: Job Event Candidates
    description: |
      An Event Candidate is the candidate participating in the event. Each candidate object contains the id, the candidate id, and the data of the candidate.
  - name: Job Offers
    description: |
      You create job offers by providing details such as proposed start date, job assignment, salary, or other compensation. 
      You extend job offers to candidates. Candidates receive the offers, consider the content, and respond to the offers by either accepting or declining them.
      When the candidate accepts the job offer, the candidate is handed over to the HR specialist who finalizes the HR records for this worker.
  - name: Job Offer Variables
    description: |
      The variables related to the offer.

      **Built-in Variables:**

      We’ve created a list of common variables that you can use.
      When writing your offer title and body in a word processor, include variables you wish to utilize in square brackets, e.g.: [candidate_name].

        General variables:
        - Today's Date - `[date_today]` e.g.: 2023-08-01

        Candidate related variables:
        - Candidate ID - `[candidate_id]` e.g.: d5a7a5b7-a4a3-49e7-9c69-b44d2cbe15cf
        - Candidate Name - `[candidate_name]` e.g.: John Doe
        - Candidate Number - `[candidate_number]` e.g.: CAND1001
        - Candidate Signature - `[candidate_signature]`

        Job related variables:
        - Job ID - `[job_id]` e.g.: d5a7a5b7-a4a3-49e7-9c69-b44d2cbe15cf
        - Job Name - `[job_name]` e.g.: Senior Backend Developer
        - Job Responsibility - `[job_responsibility]`

        Salary related variables:
        - Salary Amount - `[salary_amount]` e.g.: 25
        - Salary Frequency - `[salary_frequency]` e.g.: Hourly
        - Salary Currency - `[salary_currency]` e.g.: USD
        - Salary - `[salary]` e.g.: 25 USD per Hourly
        - Bonus - `[bonus]`

        Offer related variables:
        - Offer Expiration Date - `[offer_expiration_date]` e.g.: 2023-08-09

        Sender related variables:
        - Sender Name - `[sender_name]` e.g.: John Appleseed
        - Sender Title - `[sender_title]` e.g.: Hiring Manager
        - Sender Signature - `[sender_signature]`
  - name: Job Offer Documents
    description: |
      The documents related to the offer (Offer letter & other documents)
  # Candidate Sorting
  - name: Sortings
    description: |
      You can sort candidates with conditional sorting for each stage in your pipeline.
      The sorting will help recuiters move qualified top candidates to the next stage easily.
  - name: Sorting Conditions
    description: |
      Sorting Conditions.
  - name: Sorting Associations
    description: |
      Sorting Associations.
  - name: Sorting Association Candidates
    description: |
      Association Candidates.
  # Talent Pool
  - name: Pools
    description: |
      The Talent Pool is a place to upload and store candidates who do not fit in an active job, but who you'd like to consider for future roles.
  - name: Pool Members
    description: |
      Admins on your account have access to every talent pool and its candidate, but do not need to be included in the team member if the talent pool is not relevant to them.

      They can add or remove themselves from the team member of the talent pool at any time.

      Other members must be added to the talent pool's member to have access to candidates. 

      If they are not on the talent pool members they will not be able to see or interact with candidates for that talent pool.
  - name: Pool Candidates
  # Onboarding
  - name: onboarding-overview
    x-displayName: Onboarding Overview
    description: |
      The Reworkly Onboarding can be used to assign and track the progress of basic onboarding activities after a candidate has been hired. This can apply to basic company-wide onboarding or role-specific onboarding activities. Specific tasks and deadlines can be tracked within the Reworkly Onboarding to ensure the new hire is on track.
  - name: onboarding-datamodel
    x-displayName: Onboarding Data Model
    description: |
      The data model of the Onboarding is represented by the following conceptual model. 
      This will make it easier for you to understand the Onboarding Endpoints.

      <a href="/img/datamodel/reworkly_onboarding.png" target="_blank">
        <img src="/img/datamodel/reworkly_onboarding.png" alt="Onboarding Data Model" />
      </a>

      _Click to enlarge the image._
  - name: onboarding-endpoints
    x-displayName: Onboarding Endpoints
    description: |
      **Endpoints:**
  # Employees
  - name: employees-overview
    x-displayName: Employees Overview
    description: |
      Manage your Employees' data, and make informed decisions.
  - name: employees-datamodel
    x-displayName: Employee Data Model
    description: |
      The data model of the Employees is represented by the following conceptual model. 
      This will make it easier for you to understand the Employees Endpoints.

      <a href="/img/datamodel/reworkly_employees.png" target="_blank">
        <img src="/img/datamodel/reworkly_employees.png" alt="Employee Data Model" />
      </a>

      _Click to enlarge the image._
  - name: employees-endpoints
    x-displayName: Employees Endpoints
    description: |
      **Endpoints:**
  # Time & Scheduling
  - name: time-overview
    x-displayName: Time & Scheduling Overview
    description: |
      Time and Scheduling helps you track your team's attendance, configure schedule, manage time logs.
  - name: time-datamodel
    x-displayName: Time & Scheduling Data Model
    description: |
      The data model of the Time & Scheduling is represented by the following conceptual model. 
      This will make it easier for you to understand the Time & Scheduling Endpoints.

      <a href="/img/datamodel/reworkly_time.png" target="_blank">
        <img src="/img/datamodel/reworkly_time.png" alt="Time & Scheduling Data Model" />
      </a>

      _Click to enlarge the image._
  - name: time-endpoints
    x-displayName: Time & Scheduling Endpoints
    description: |
      **Endpoints:**
  # Payroll
  - name: payroll-overview
    x-displayName: Payroll Overview
    description: |
      Payroll is a rules-based product. All payroll processes, calculations, and results are determined by a set of rules that you can easily build.
  - name: payroll-datamodel
    x-displayName: Payroll Data Model
    description: |
      The data model of the Payroll is represented by the following conceptual model. 
      This will make it easier for you to understand the Payroll Endpoints.

      <a href="/img/datamodel/reworkly_payroll.png" target="_blank">
        <img src="/img/datamodel/reworkly_payroll.png" alt="Payroll Data Model" />
      </a>

      _Click to enlarge the image._
  - name: payroll-endpoints
    x-displayName: Payroll Endpoints
    description: |
      **Endpoints:**
  # List of Values
  - name: lov-overview
    x-displayName: LOV Overview
    description: |
      LOV is a static or dynamic set of values used to display a specific type of page item, such as popup lists of values, a select list, a check box, a radio group, or multiple select lists.
  - name: lov-datamodel
    x-displayName: LOV Data Model
    description: |
      The data model of the LOV is represented by the following conceptual model. 
      This will make it easier for you to understand the LOV Endpoints.

      <a href="/img/datamodel/reworkly_lov.png" target="_blank">
        <img src="/img/datamodel/reworkly_lov.png" alt="LOV Data Model" />
      </a>

      _Click to enlarge the image._
  - name: lov-endpoints
    x-displayName: LOV Endpoints
    description: |
      ### Endpoints:
      - [Lookups](#tag/lov-ookups)
      - [Lookup Values](#tag/lov-lookup-values)
      - [Translations](#tag/lov-translations)
  - name: lov-lookups
    x-displayName: Lookups
    description: |
      Lookups are lists of values in applications. You define a list of values as a lookup consisting of a set of lookup values.
      Lookup and Lookup values are translated name and description. End users see the list of translated names and descriptions as the available values for an object.
  - name: lov-lookup-values
    x-displayName: Lookup Values
    description: |
      Lookups provide lists of values where valid values appear on a list with no duplicate values. 
      For example, an application might store the values Male and Female in a Gender in a table, 
      but when displaying those values in the user interface, Male or Female (or their translated equivalents) should be available for end users to select.
  - name: lov-translations
    x-displayName: Translations
    description: |
      You can translate the lookups and values that you defined to the preferred language(s) without changing the language session of the application. 
      When you edit a particular language entry, you can modify the translated name and description to the language in which you want the lookup to appear.
      Once the updates are made, the end-users can view the lookup in the translated text.
  # Profile
  - name: profile-overview
    x-displayName: Profile Overview
    description: |
      Profiles are widely used by organizations to describe the attributes of jobs or individuals. 
      Typically, profiles summarize the competencies, qualifications, and skills of any type of objects. 
      Profiles are valuable for tracking persons' skills, competencies, and accomplishments, in career planning, 
      for identifying training needs, for performance management, and in the recruitment process for identifying job requirements and suitable applicants.
  - name: profile-datamodel
    x-displayName: Profile Data Model
    description: |
      The data model of the Profile is represented by the following conceptual model. 
      This will make it easier for you to understand the Profile Endpoints.

      <a href="/img/datamodel/reworkly_profile.png" target="_blank">
        <img src="/img/datamodel/reworkly_profile.png" alt="LOV Data Model" />
      </a>

      _Click to enlarge the image._
  - name: profile-endpoints
    x-displayName: Profile Endpoints
    description: |
      ### Profile Management:
      - [Profiles](#tag/profile-profiles)
      - [Profile Names](#tag/profile-profile-names)
      - [Profile Images](#tag/profile-profile-images)
      - [Profile Emails](#tag/profile-profile-emails)
      - [Profile Phones](#tag/profile-profile-phones)
      - [Profile Webs](#tag/profile-profile-webs)
      - [Profile Socials](#tag/profile-profile-socials)
      - [Profile Addresses](#tag/profile-profile-addresses)
      - [Profile Educations](#tag/profile-profile-educations)
      - [Profile Languages](#tag/profile-profile-languages)
      - [Profile Skills](#tag/profile-profile-skills)
      - [Profile Experiences](#tag/profile-profile-experiences)
      - [Profile Citizenships](#tag/profile-profile-citizenships)
      - [Profile Tests](#tag/profile-profile-tests)
      - [Profile Test Components](#tag/profile-profile-test-components)
      - [Profile Awards](#tag/profile-profile-awards)
      - [Profile Attachments](#tag/profile-profile-attachments)
      - [Profile Contents](#tag/profile-profile-contents)

      ### Profile Types:
      - [Profile Types](#tag/profile-profile-types)
      - [Profile Type Attributes](#tag/profile-profile-type-attributes)
      - [Content Types](#tag/profile-content-types)
      - [Content Type Attributes](#tag/profile-content-type-attributes)

      ### Rating Scales:
      - [Rating Scales](#tag/profile-rating-scales)
      - [Rating Scale Levels](#tag/profile-rating-scale-levels)
  - name: profile-profile-types
    x-displayName: Profile Types
    description: |
      The profile type defines the content types and attributes that define the structure of your profiles.
  - name: profile-profile-type-attributes
    x-displayName: Profile Type Attributes
    description: |
      When you define a profile type, you specify attributes of the profile type that the user can select when creating a profile. 

      For example, suppose that you create a profile type and specify that it can be linked to candidate id and address. 
      When users create a profile based on that profile type, they can only select candidate id and address for the new profile. 

      Every profile type consists of a required attribute at least for identifying a profile.
  - name: profile-content-types
    x-displayName: Content Types
    description: |
      A content type is a broad definition of a group of items that can be added to the profile type. 
      Within a content type, specify attributes for all items of this type can or must have.
  - name: profile-content-type-attributes
    x-displayName: Content Type Attributes
    description: |
      When you add a content type to a profile type, you add the attributes that define the information entered for that specific profile type.
  - name: profile-profiles
    x-displayName: Profiles
    description: |
      Every user and candidate has a profile. It includes personal information like firstname, lastname, image, and social accounts, educations, experiences, skills and attachments.

      **Built-in Content Types** - Names, Images, Emails, Phones, Webs, Socials, Addresses, Educations, Languages, Skills, Experiences, and Attachments.

      **Custom Content Type:**
        - [Profile Contents](#tag/profile-profile-contents)
  - name: profile-profile-names
    x-displayName: Profile Names
    description: |
      Profile Names is a list of names for the profile. 

      Each entry contains the following fields:
        - Type - e.g: Full Name
        - Text - e.g: John Doe
  - name: profile-profile-images
    x-displayName: Profile Images
    description: |
      Profile Images is a list of images for the profile. 

      Each entry contains the following fields:
        - Type - e.g: Profile
        - URL - e.g: htts://github.com/aircampi.png
        - description - e.g: GitHub Profile
  - name: profile-profile-emails
    x-displayName: Profile Emails
    description: |
      Profile Emails is a list of emails for the profile. 

      Each entry contains the following fields:
        - Type - e.g: Work
        - address - e.g: hello@aircampi.com
        - description - e.g: Hello Mail
  - name: profile-profile-phones
    x-displayName: Profile Phones
    description: |
      Profile Phones is a list of phones for the profile. 

      Each entry contains the following fields:
        - Type - e.g: Work
        - Country - e.g: +976
        - number - e.g: 99112233
        - extension - e.g: 1
        - description - e.g: Work Phone
  - name: profile-profile-webs
    x-displayName: Profile Webs
    description: |
      Profile Webs is a list of webs for the profile. 

      Each entry contains the following fields:
        - Type - e.g: Personal
        - address - e.g: htts://github.com/aircampi
        - description - e.g: GitHub Profile
  - name: profile-profile-socials
    x-displayName: Profile Socials
    description: |
      Profile Socials is a list of social accounts, and you can provide one social account url for each social network type. 

      Each entry contains the following fields:
        - Type - e.g: Facebook
        - Username - e.g: aircampi.com
        - URL - e.g: https://www.facebook.com/aircampi
  - name: profile-profile-addresses
    x-displayName: Profile Addresses
    description: |
      Profile Addresses is a list of addresses for the profile. 

      Each entry contains the following fields:
        - Type - e.g: Home Address
        - Country - e.g: United States
        - state - e.g: 
        - zipcode - e.g: 
        - City - e.g: Washington D.C
        - line_1 - e.g: bayanzurkh district
        - line_2 - e.g: Peace avenue
        - line_3 - e.g: Building III
  - name: profile-profile-educations
    x-displayName: Profile Educations
    description: |
      Profile Educations is a list of education entries. 

      Each entry may contain the following fields:
        - School
        - Level
        - Degree
        - Field of Study
        - Start at
        - End at
        - Completed - True if still study there
        - Description
  - name: profile-profile-languages
    x-displayName: Profile Languages
    description: |
      Profile Languages is a list of language skills for the profile. 

      Each entry contains the following fields:
        - Language
        - Native
        - profile-rating-scales
        - Writing Level
        - Reading Level
        - Listening Level
        - Speaking Level
        - Overall Level
        - Overall Score
        - Assessment At
        - Description
  - name: profile-profile-skills
    x-displayName: Profile Skills
    description: |
      Profile Skill is a list of skills.
  - name: profile-profile-experiences
    x-displayName: Profile Experiences
    description: |
      Profile Experiences is a list of employments. 

      Each entry may contain the following fields:
        - Title
        - Company
        - Industry
        - Start at
        - End at
        - Current - True if still works there
        - Description
  - name: profile-profile-attachments
    x-displayName: Profile Attachments
    description: |
      Profile Attachments is a list of attachments.
  - name: profile-profile-citizenships
    x-displayName: Profile Citizenships
    description: |
      Profile Citizenship is a list of citizenship data.

      Each entry may contain the following fields:
      - Country
      - Nation ID
      - Issued at
      - Expiry at
      - Description
  - name: profile-profile-tests
    x-displayName: Profile Tests
    description: |
      Profile Test is a list of test or exam data.

      Each entry may contain the following fields:
      - Type
      - Score
      - Test at
      - Description
  - name: profile-profile-test-components
    x-displayName: Profile Test Components
    description: |
      Profile Test Component is a list of test components such as speaking, listening for the IELTS.

      Each entry may contain the following fields:
      - Type
      - Score
      - Test at
      - Description
  - name: profile-profile-awards
    x-displayName: Profile Awards
    description: |
      Profile Award is a list of award or honor data.

      Each entry may contain the following fields:
      - Type
      - Name
      - Number
      - Description
      - Issued at
      - Expiry at
  - name: profile-profile-contents
    x-displayName: Profile Contents
    description: |
      Profile Content is a list of contents defined in the content type of the profile type.
  - name: profile-rating-scales
    x-displayName: Rating Scales
    description: |
      Rating scales define the values that can be used to rate an profile's performance or level of proficiency.
  - name: profile-rating-scale-levels
    x-displayName: Rating Scale Levels
    description: |
      The rating scale defines the qualitative values, such as A, B, C, or D, that the system uses to rate or score an profile's performance. 
      Each qualitative value can have a rating level, and numeric points in levels of the rating scale.
    # Integration
  - name: Integration Overview
    description: |
      Register your assessments, background checks, or reference checks service as integration in Reworkly Recruiting.
  - name: Assessment
    description: |
      You use assessments to assess and measure the knowledge, skills, abilities, and attributes of candidates for a job.

      When you create a job, you add assessments in the Screening Services section. You can add one or more assessment screening packages. 
      After you select the assessment partner and user account, you need to decide if candidates take the assessment when applying for a job, 
      or during the candidate selection process, or both.
  - name: Background Check
    description: |
      You can use a background check during the candidate selection process to investigate a candidate's background before hiring them.

      A check on a candidate's background may include verifications such as employment history, education, criminal records. 
      After the background check is complete, candidates are ready to be moved to the next step in the recruiting process.

      Your administrator configures when the background check is automatically triggered during the candidate selection process. 
      The background check partner obtains the candidate's info and completes the background check. You then receive a notification.

      If you create a job based on a template which contains background checks, the background checks are added to the job. 
      You can edit the selected background check packages. If you create a requisition using a blank form, you can add background checks in the Screening Services section. 
      You can add one or more background check packages, usually multiple packages with a single screening.
  - name: Evaluation/Rating
    description: |
      Candidate ratings/evaluations are a critical aspect of the hiring process. 
      They help recruiters and hiring managers collect feedback from interviewers and make data-driven decisions.

      **Simple Rating** <br/>
      Rate the candidate with a star, thumbs up, or thumbs down rating, depending on how interested you are in moving the candidate to the next stage in the pipeline.

      **Scorecard Evaluation** <br/>

      **Rubric** <br/>
      Rubric is a scoring tool you can use to evaluate candidate.
paths:
  # Server Health
  /health:
    get:
      tags:
        - server-health
      summary: Check Health
      description: Check Health
      operationId: checkServerHealth
  # Server Settings
  /settings:
    get:
      tags:
        - server-settings
      summary: Get Server Settings
      description: Get a server settings.
      operationId: getServerSettings
      security:
        - Scopes:
            - "read:server_settings"
    put:
      tags:
        - server-settings
      summary: Update Server Settings
      description: Update a server settings. Updates all fields in a settings.
      operationId: updateServerSettings
      security:
        - Scopes:
            - "update:server_settings"
    patch:
      tags:
        - server-settings
      summary: Patch Server Settings
      description: Patch a server settings. Updates one or more fields in a settings. The operation updates passed fields only.
      operationId: patchServerSettings
      security:
        - Scopes:
            - "update:server_settings"
  # Job Management
  /jobs:
    get:
      tags:
        - Jobs
      summary: Get Jobs
      description: |
        Returns a list of jobs that the requesting user is permitted to view.
      operationId: getJobs
      security:
        - Scopes:
            - "read:jobs"
    post:
      tags:
        - Jobs
      summary: Create Job
      description: |
        Create an Job.
      operationId: createJob
      security:
        - Scopes:
            - "create:jobs"
  /jobs/{job_id}:
    get:
      tags:
        - Jobs
      summary: Get Job
      description: |
        Retrieve a single job details.
      operationId: getJob
      security:
        - Scopes:
            - "read:jobs"
    put:
      tags:
        - Jobs
      summary: Update Job
      description: |
        You can update fields of an job after the job is created. The following fields can be updated any time after the job is created.

        **Available fields to update:**
          - name
          - description
          - workload
          - temporary
          - function
          - department
          - location
          - industry
          - benefits
          - salary_min
          - salary_max
          - salary_currency
          - metadata
          - app_metadata
      operationId: updateJob
      security:
        - Scopes:
            - "update:jobs"
    patch:
      tags:
        - Jobs
      summary: Patch Job
      description: |
        Updates one or more fields in an job. The operation updates passed fields only.

        **Available fields to update:**
          - name
          - description
          - workload
          - temporary
          - function
          - department
          - location
          - industry
          - benefits
          - salary_min
          - salary_max
          - salary_currency
          - metadata
          - app_metadata
      operationId: patchJob
      security:
        - Scopes:
            - "update:jobs"
    delete:
      tags:
        - Jobs
      summary: Delete Job
      description: |
        Deleting a job will completely remove the job and all candidates as well as any data associated with it.
      operationId: deleteJob
      security:
        - Scopes:
            - "delete:jobs"
  /jobs/{job_id}/status:
    post:
      tags:
        - Jobs
      summary: Change Job Status
      description: |
        Changes status of an job to the status specified in the request body.

        Statuses:
          - Draft <br/>
            _A Draft job is a job that is saved but not yet published._
          - Published <br/>
            _A Published job can be visible for candidates on any available sources such as career page. Candidates will be able to find your published job and submit applications._ 
          - Published for Internal <br/> 
            _A Published interal job is not visible on your career page. Only people with the job's direct link can see it. Candidates can apply. You can access the job's pipeline._
          - Closed <br/>
            _Closed jobs are only visible to members of the recruiting team for the job. All Super Admins can see closed jobs._
          - Archived <br/>
            _Archived jobs enter a 'read-only' mode. Candidates remain in your account and can be copied or moved to other jobs, but you are not able to interact with their profiles._

      operationId: changeJobStatus
      security:
        - Scopes:
            - "update:jobs"
  /jobs/{job_id}/duplicate:
    post:
      tags:
        - Jobs
      summary: Duplicate Job
      description: |
        Duplicate an Job.
      operationId: duplicateJob
      security:
        - Scopes:
            - "read:jobs"
            - "create:jobs"
  /jobs/{job_id}/stages:
    get:
      tags:
        - Job Stages
      summary: Get Stages
      description: |
        Returns a list of stages of the job.
      operationId: getJobStages
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_stages"
    post:
      tags:
        - Job Stages
      summary: Add Stage
      description: |
        Add a stage to the job.
      operationId: createJobStage
      security:
        - Scopes:
            - "update:jobs"
            - "create:job_stages"
  /jobs/{job_id}/stages/{stage_id}:
    get:
      tags:
        - Job Stages
      summary: Get Stage
      description: |
        Retrieve a single stage details.
      operationId: getJobStage
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_stages"
    put:
      tags:
        - Job Stages
      summary: Update Stage
      description: |
        You can update fields of a stage after the stage is added.
      operationId: updateJobStage
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_stages"
    patch:
      tags:
        - Job Stages
      summary: Patch Stage
      description: |
        Updates one or more fields in a stage. The operation updates passed fields only.
      operationId: patchJobStage
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_stages"
    delete:
      tags:
        - Job_stages
      summary: Remove Stage
      description: |
        You can remove a single stage from the job with this operation.
      operationId: deleteJobStage
      security:
        - Scopes:
            - "update:jobs"
            - "delete:job_stages"
  /jobs/{job_id}/sources:
    get:
      tags:
        - Job Sources
      summary: Get Sources
      description: |
        Returns a list of sources of the job.
      operationId: getJobSources
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_sources"
    post:
      tags:
        - Job Sources
      summary: Add Source
      description: |
        Add a source to the job.
      operationId: createJobSource
      security:
        - Scopes:
            - "update:jobs"
            - "create:job_sources"
  /jobs/{job_id}/sources/{source_id}:
    get:
      tags:
        - Job Sources
      summary: Get Source
      description: |
        Retrieve a single source details.
      operationId: getJobSource
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_sources"
    put:
      tags:
        - Job Sources
      summary: Update Source
      description: |
        You can update fields of a source after the source is added.
      operationId: updateJobSource
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_sources"
    patch:
      tags:
        - Job Sources
      summary: Patch Source
      description: |
        Updates one or more fields in a source. The operation updates passed fields only.
      operationId: patchJobSource
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_sources"
    delete:
      tags:
        - Job Sources
      summary: Remove Source
      description: |
        You can remove a single source from the job with this operation.
      operationId: deleteJobSource
      security:
        - Scopes:
            - "update:jobs"
            - "delete:job_sources"
  /jobs/{job_id}/members:
    get:
      tags:
        - Job Members
      summary: Get Members
      description: |
        Returns a list of members of the job that the requester is permitted to view.
      operationId: getJobMembers
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_members"
    post:
      tags:
        - Job Members
      summary: Add Members
      description: |
        Add Members to the job.
      operationId: createJobMembers
      security:
        - Scopes:
            - "update:jobs"
            - "create:job_members"
    delete:
      tags:
        - Job Members
      summary: Remove Members
      description: |
        You can remove one and more members from an job with this operation.
      operationId: deleteJobMembers
      security:
        - Scopes:
            - "update:jobs"
            - "delete:job_members"
  /jobs/{job_id}/members/{user_id}:
    get:
      tags:
        - Job Members
      summary: Get Member
      description: |
        Retrieve single member details from the job.
      operationId: getJobMember
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_members"
    delete:
      tags:
        - Job Members
      summary: Remove Member
      description: |
        You can remove a single member from an job with this operation. 

        This only removes the specified member from the job and does not affect their user profile.
      operationId: deleteJobMember
      security:
        - Scopes:
            - "update:jobs"
            - "delete:job_members"
  /jobs/{job_id}/candidates:
    get:
      tags:
        - Job Candidates
      summary: Get Candidates
      description: |
        Returns a list of candidates of the job.
      operationId: getCandidates
      security:
        - Scopes:
            - "read:candidates"
    post:
      tags:
        - Job Candidates
      summary: Add Candidate
      description: |
        Add a candidate.
      operationId: createCandidate
      security:
        - Scopes:
            - "create:candidates"
  /jobs/{job_id}/candidates/{candidate_id}:
    get:
      tags:
        - Job Candidates
      summary: Get Candidate
      description: |
        Retrieve a single candidate details.
      operationId: getCandidate
      security:
        - Scopes:
            - "read:candidates"
    put:
      tags:
        - Job Candidates
      summary: Update Candidate
      description: |
        You can update fields of a candidate after the candidate is created.
      operationId: updateCandidate
      security:
        - Scopes:
            - "update:candidates"
    patch:
      tags:
        - Job Candidates
      summary: Patch Candidate
      description: |
        Updates one or more fields in a candidate. The operation updates passed fields only.
      operationId: patchCandidate
      security:
        - Scopes:
            - "update:candidates"
    delete:
      tags:
        - Job Candidates
      summary: Delete Candidate
      description: |
        Delete a candidate.
      operationId: deleteCandidate
      security:
        - Scopes:
            - "delete:candidates"
  /jobs/{job_id}/candidates/{candidate_id}/status:
    post:
      tags:
        - Job Candidates
      summary: Change Candidate Status
      description: |
        Changes status of a candidate to the status specified in the request body.
      operationId: changeCandidateStatus
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/{candidate_id}/move:
    post:
      tags:
        - Job Candidates
      summary: Move Candidate
      description: |
        Moves the candidate to another stage.
      operationId: moveCandidate
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/{candidate_id}/disqualify:
    post:
      tags:
        - Job Candidates
      summary: Disqualify Candidate
      description: |
        Disqualifies a candidate.
      operationId: disqualifyCandidate
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/{candidate_id}/revert:
    post:
      tags:
        - Job Candidates
      summary: Revert Candidate
      description: |
        Reverts a candidate's disqualification.
      operationId: revertCandidate
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/{candidate_id}/duplicate:
    post:
      tags:
        - Job Candidates
      summary: Duplicate Candidate
      description: |
        Copy the candidate to another job.
      operationId: duplicateCandidate
      security:
        - Scopes:
            - "update:candidates"
            - "create:candidates"
  /jobs/{job_id}/candidates/{candidate_id}/transfer:
    post:
      tags:
        - Job Candidates
      summary: Transfer Candidate
      description: |
        Moves a candidate to another job.
      operationId: transferCandidate
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/move:
    post:
      tags:
        - Job Candidates
      summary: Move Candidates (Bulk Action)
      description: |
        Moves candidates to another stage. (Bulk Action)
      operationId: moveCandidates
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/disqualify:
    post:
      tags:
        - Job Candidates
      summary: Disqualify Candidates (Bulk Action)
      description: |
        Disqualifies candidates (Bulk Action).
      operationId: disqualifyCandidates
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/revert:
    post:
      tags:
        - Job Candidates
      summary: Revert Candidates (Bulk Action)
      description: |
        Reverts candidates' disqualification (Bulk Action).
      operationId: revertCandidates
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/candidates/duplicate:
    post:
      tags:
        - Job Candidates
      summary: Duplicate Candidates (Bulk Action)
      description: |
        Copy candidates to another job (Bulk Action).
      operationId: duplicateCandidates
      security:
        - Scopes:
            - "update:candidates"
            - "create:candidates"
  /jobs/{job_id}/candidates/transfer:
    post:
      tags:
        - Job Candidates
      summary: Transfer Candidates (Bulk Action)
      description: |
        Moves candidates to another job (Bulk Action).
      operationId: transferCandidates
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/offers:
    get:
      tags:
        - Job Offers
      summary: Get Offers
      description: |
        Returns a list of offers of the candidate.
      operationId: getJobOffers
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_offers"
    post:
      tags:
        - Job Offers
      summary: Add Offer
      description: |
        Add a offer to the candidate.
      operationId: createJobOffer
      security:
        - Scopes:
            - "update:jobs"
            - "create:job_offers"
  /jobs/{job_id}/offers/{offer_id}:
    get:
      tags:
        - Job Offers
      summary: Get Offer
      description: |
        Retrieve a single offer details.
      operationId: getJobOffer
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_offers"
    put:
      tags:
        - Job Offers
      summary: Update Offer
      description: |
        You can update fields of a offer after the offer is added.
      operationId: updateJobOffer
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_offers"
    patch:
      tags:
        - Job Offers
      summary: Patch Offer
      description: |
        Updates one or more fields in a offer. The operation updates passed fields only.
      operationId: patchJobOffer
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_offers"
    delete:
      tags:
        - Job Offers
      summary: Remove Offer
      description: |
        You can remove a single offer from the candidate and the job.
      operationId: deleteJobOffer
      security:
        - Scopes:
            - "update:jobs"
            - "delete:job_offers"
  /jobs/{job_id}/offers/{offer_id}/status:
    post:
      tags:
        - Job Offers
      summary: Change Offer Status
      description: |
        Changes status of a offer to the status specified in the request body.
      operationId: changeJobOfferStatus
      security:
        - Scopes:
            - "update:candidates"
            - "update:job_offers"
  /jobs/{job_id}/offers/{offer_id}/variables:
    get:
      tags:
        - Job Offer Variables
      summary: Get Variables
      description: |
        Returns a list of variables of the offer.
      operationId: getJobOfferVariables
      security:
        - Scopes:
            - "read:job_offer"
            - "read:job_offer_variables"
    post:
      tags:
        - Job Offer Variables
      summary: Add Variable
      description: |
        Add a variable to the offer.
      operationId: createJobOfferVariable
      security:
        - Scopes:
            - "update:job_offers"
            - "create:job_offer_variables"
  /jobs/{job_id}/offers/{offer_id}/variables/{variable}:
    get:
      tags:
        - Job Offer Variables
      summary: Get Variable
      description: |
        Retrieve a single variable.
      operationId: getJobOfferVariable
      security:
        - Scopes:
            - "read:job_offers"
            - "read:job_offer_variables"
    put:
      tags:
        - Job Offer Variables
      summary: Update Variable
      description: |
        You can update fields of a variable after the variable is added.
      operationId: updateJobOfferVariable
      security:
        - Scopes:
            - "update:job_offers"
            - "update:job_offer_variables"
    patch:
      tags:
        - Job Offer Variables
      summary: Patch Variable
      description: |
        Updates one or more fields in a variable. The operation updates passed fields only.
      operationId: patchJobOfferVariable
      security:
        - Scopes:
            - "update:job_offers"
            - "update:job_offer_variables"
    delete:
      tags:
        - Job Offer Variables
      summary: Remove Variable
      description: |
        You can remove a single variable from the offer with this operation.
      operationId: deleteJobOfferVariable
      security:
        - Scopes:
            - "update:job_offers"
            - "delete:job_offer_variables"
  /jobs/{job_id}/offers/{offer_id}/documents:
    get:
      tags:
        - Job Offer Documents
      summary: Get Documents
      description: |
        Returns a list of documents of the offer.
      operationId: getJobOfferDocuments
      security:
        - Scopes:
            - "read:job_offer"
            - "read:job_offer_documents"
    post:
      tags:
        - Job Offer Documents
      summary: Add Document
      description: |
        Add a document to the offer.
      operationId: createJobOfferDocument
      security:
        - Scopes:
            - "update:job_offers"
            - "create:job_offer_documents"
  /jobs/{job_id}/offers/{offer_id}/documents/{document_id}:
    get:
      tags:
        - Job Offer Documents
      summary: Get Document
      description: |
        Retrieve a single document.
      operationId: getJobOfferDocument
      security:
        - Scopes:
            - "read:job_offers"
            - "read:job_offer_documents"
    put:
      tags:
        - Job Offer Documents
      summary: Update Document
      description: |
        You can update fields of a document after the document is added.
      operationId: updateJobOfferDocument
      security:
        - Scopes:
            - "update:job_offers"
            - "update:job_offer_documents"
    patch:
      tags:
        - Job Offer Documents
      summary: Patch Document
      description: |
        Updates one or more fields in a document. The operation updates passed fields only.
      operationId: patchJobOfferDocument
      security:
        - Scopes:
            - "update:job_offers"
            - "update:job_offer_documents"
    delete:
      tags:
        - Job Offer Documents
      summary: Remove Document
      description: |
        You can remove a single document from the offer with this operation.
      operationId: deleteJobOfferDocument
      security:
        - Scopes:
            - "update:job_offers"
            - "delete:job_offer_documents"
  /jobs/{job_id}/events:
    get:
      tags:
        - Job Events
      summary: Get Events
      description: |
        Returns a list of events of the job.
      operationId: getJobEvents
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_events"
    post:
      tags:
        - Job Events
      summary: Add Event
      description: |
        Add an event to the job.
      operationId: createJobEvent
      security:
        - Scopes:
            - "update:jobs"
            - "create:job_events"
  /jobs/{job_id}/events/{event_id}:
    get:
      tags:
        - Job Events
      summary: Get Event
      description: |
        Retrieve a single event details.
      operationId: getJobEvent
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_events"
    put:
      tags:
        - Job Events
      summary: Update Event
      description: |
        You can update fields of an event after the event is added.
      operationId: updateJobEvent
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
    patch:
      tags:
        - Job Events
      summary: Patch Event
      description: |
        Updates one or more fields in an event. The operation updates passed fields only.
      operationId: patchJobEvent
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
    delete:
      tags:
        - Job Events
      summary: Remove Event
      description: |
        You can remove a single event from the job with this operation.
      operationId: deleteJobEvent
      security:
        - Scopes:
            - "update:jobs"
            - "delete:job_events"
  /jobs/{job_id}/events/{event_id}/organizers:
    get:
      tags:
        - Job Event Organizers
      summary: Get Organizers
      description: |
        Returns a list of organizers of the event that the requester is permitted to view.
      operationId: getJobEventOrganizers
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_events"
            - "read:job_event_organizers"
    post:
      tags:
        - Job Event Organizers
      summary: Add Organizers
      description: |
        Add Organizers to the event of the job.
      operationId: createJobEventOrganizers
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
            - "create:job_event_organizers"
    delete:
      tags:
        - Job Event Organizers
      summary: Remove Organizers
      description: |
        You can remove one and more organizers from an event with this operation.
      operationId: deleteJobEventOrganizers
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
            - "delete:job_event_organizers"
  /jobs/{job_id}/events/{event_id}/organizers/{organizer_id}:
    get:
      tags:
        - Job Event Organizers
      summary: Get Organizer
      description: |
        Retrieve single organizer details from the event of the job.
      operationId: getJobEventOrganizer
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_events"
            - "read:job_event_organizers"
    delete:
      tags:
        - Job Event Organizers
      summary: Remove Organizer
      description: |
        You can remove a single organizer from an event with this operation.
      operationId: deleteJobEventOrganizer
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
            - "delete:job_event_organizers"
  /jobs/{job_id}/events/{event_id}/organizers/{organizer_id}/status:
    post:
      tags:
        - Job Event Organizers
      summary: Change Organizer Status
      description: |
        Changes status of an organizer to the status specified in the request body.
      operationId: changeJobEventOrganizerStatus
      security:
        - Scopes:
            - "update:candidates"
  /jobs/{job_id}/events/{event_id}/candidates:
    get:
      tags:
        - Job Event Candidates
      summary: Get Candidates
      description: |
        Returns a assigned list of candidates of the event that the requester is permitted to view.
      operationId: getJobEventCandidates
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_events"
            - "read:job_event_candidates"
    post:
      tags:
        - Job Event Candidates
      summary: Add Candidates
      description: |
        Add Candidates to the event of the job.
      operationId: createJobEventCandidates
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
            - "create:job_event_candidates"
    delete:
      tags:
        - Job Event Candidates
      summary: Remove Candidates
      description: |
        You can remove one and more candidates from an event with this operation.
      operationId: deleteJobEventCandidates
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
            - "delete:job_event_candidates"
  /jobs/{job_id}/events/{event_id}/candidates/{candidate_id}:
    get:
      tags:
        - Job Event Candidates
      summary: Get Candidate
      description: |
        Retrieve single candidate details from the event of the job.
      operationId: getJobEventCandidate
      security:
        - Scopes:
            - "read:jobs"
            - "read:job_events"
            - "read:job_event_candidates"
    delete:
      tags:
        - Job Event Candidates
      summary: Remove Candidate
      description: |
        You can remove a single candidate from an event with this operation.
      operationId: deleteJobEventCandidate
      security:
        - Scopes:
            - "update:jobs"
            - "update:job_events"
            - "delete:job_event_candidates"
  # Candidate Sorting
  /sortings:
    get:
      tags:
        - Sortings
      summary: Get Sortings
      description: |
        Returns a list of sortings that the requesting user is permitted to view.
      operationId: getSortings
      security:
        - Scopes:
            - "read:sortings"
    post:
      tags:
        - Sortings
      summary: Create Sorting
      description: |
        Create a sorting.
      operationId: createSorting
      security:
        - Scopes:
            - "create:sortings"
  /sortings/{sorting_id}:
    get:
      tags:
        - Sortings
      summary: Get Sorting
      description: |
        Returns a single sorting details.
      operationId: getSorting
      security:
        - Scopes:
            - "read:sortings"
    put:
      tags:
        - Sortings
      summary: Update Sorting
      description: |
        You can update fields of a sorting after the sorting is created. The following fields can be updated any time after the sorting is created.

        **Available fields to update:**
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateSorting
      security:
        - Scopes:
            - "update:sortings"
    patch:
      tags:
        - Sortings
      summary: Patch Sorting
      description: |
        Updates one or more fields in a sorting. The operation updates passed fields only.

        **Available fields to update:**
        - name
        - description
        - metadata
        - app_metadata
      operationId: patchSorting
      security:
        - Scopes:
            - "update:sortings"
    delete:
      tags:
        - Sortings
      summary: Delete Sorting
      description: |
        Delete a sorting.
      operationId: deleteSorting
      security:
        - Scopes:
            - "delete:sortings"
  /sortings/{sorting_id}/conditions:
    get:
      tags:
        - Sorting Conditions
      summary: Get Conditions
      description: |
        Returns a list of conditions of the sorting.
      operationId: getSortingConditions
      security:
        - Scopes:
            - "read:sortings"
            - "read:sorting_conditions"
    post:
      tags:
        - Sorting Conditions
      summary: Add Condition
      description: |
        Add a condition to the sorting.
      operationId: createSortingCondition
      security:
        - Scopes:
            - "update:sortings"
            - "create:sorting_conditions"
  /sortings/{sorting_id}/conditions/{condition_id}:
    get:
      tags:
        - Sorting Conditions
      summary: Get Condition
      description: |
        Returns a single condition details of the sorting.
      operationId: getSortingCondition
      security:
        - Scopes:
            - "read:sortings"
            - "read:sorting_conditions"
    put:
      tags:
        - Sorting Conditions
      summary: Update Condition
      description: |
        You can update fields of a condition after the condition is added.
      operationId: updateSortingCondition
      security:
        - Scopes:
            - "update:sortings"
            - "update:sorting_conditions"
    patch:
      tags:
        - Sorting Conditions
      summary: Patch Condition
      description: |
        Updates one or more fields in a condition. The operation updates passed fields only.
      operationId: patchSortingCondition
      security:
        - Scopes:
            - "update:sortings"
            - "update:sorting_conditions"
    delete:
      tags:
        - Sorting Conditions
      summary: Remove Condition
      description: |
        You can remove a single condition from the sorting.
      operationId: deleteSortingCondition
      security:
        - Scopes:
            - "update:sortings"
            - "delete:sorting_conditions"
  /sortings/{sorting_id}/associations:
    get:
      tags:
        - Sorting Associations
      summary: Get Associations
      description: |
        Returns a list of associations of the sorting.
      operationId: getSortingAssociations
      security:
        - Scopes:
            - "read:sorting"
            - "read:sorting_associations"
    post:
      tags:
        - Sorting Associations
      summary: Add Association
      description: |
        Add an association to the sorting.
      operationId: createSortingAssociation
      security:
        - Scopes:
            - "update:sortings"
            - "create:sorting_associations"
  /sortings/{sorting_id}/associations/{association_id}:
    get:
      tags:
        - Sorting Associations
      summary: Get Association
      description: |
        Returns a single association details of the sorting.
      operationId: getSortingAssociation
      security:
        - Scopes:
            - "read:sortings"
            - "read:sorting_associations"
    put:
      tags:
        - Sorting Associations
      summary: Update Association
      description: |
        You can update fields of an association after the association is added.
      operationId: updateSortingAssociation
      security:
        - Scopes:
            - "update:sortings"
            - "update:sorting_associations"
    patch:
      tags:
        - Sorting Associations
      summary: Patch Association
      description: |
        Updates one or more fields in an association. The operation updates passed fields only.
      operationId: patchSortingAssociation
      security:
        - Scopes:
            - "update:sortings"
            - "update:sorting_associations"
    delete:
      tags:
        - Sorting Associations
      summary: Remove Association
      description: |
        You can remove a single association from the sorting.
      operationId: deleteSortingAssociation
      security:
        - Scopes:
            - "update:sortings"
            - "delete:sorting_associations"
  /sortings/{sorting_id}/associations/{association_id}/terminate:
    post:
      tags:
        - Sorting Associations
      summary: Terminate Association
      description: |
        Terminate association sorting process.
      operationId: terminateSortingAssociation
      security:
        - Scopes:
            - "read:sortings"
            - "update:sorting_associations"
  /sortings/{sorting_id}/associations/{association_id}/restart:
    post:
      tags:
        - Sorting Associations
      summary: Restart Association
      description: |
        Restart association sorting process.
      operationId: restartSortingAssociation
      security:
        - Scopes:
            - "read:sortings"
            - "update:sorting_associations"
  /sortings/{sorting_id}/associations/{association_id}/candidates:
    get:
      tags:
        - Sorting Association Candidates
      summary: Get Candidates
      description: |
        Returns a list of candidates of the sorting.
      operationId: getSortingCandidates
      security:
        - Scopes:
            - "read:sorting_associations"
            - "read:sorting_association_candidates"
    post:
      tags:
        - Sorting Association Candidates
      summary: Add Candidates
      description: |
        Add candidates to the sorting.
      operationId: createSortingCandidates
      security:
        - Scopes:
            - "update:sortings"
            - "create:sorting_association_candidates"
    delete:
      tags:
        - Sorting Association Candidates
      summary: Remove Candidates
      description: |
        You can remove one and more candidates from an association with this operation.
      operationId: deleteSortingAssociationCandidates
      security:
        - Scopes:
            - "update:sorting_associations"
            - "delete:sorting_association_candidates"
  /sortings/{sorting_id}/associations/{association_id}/candidates/{candidate_id}:
    get:
      tags:
        - Sorting Association Candidates
      summary: Get Candidate
      description: |
        Returns a single candidate details of the sorting.
      operationId: getSortingCandidate
      security:
        - Scopes:
            - "read:sortings"
            - "read:sorting_association_candidates"
    delete:
      tags:
        - Sorting Association Candidates
      summary: Remove Candidate
      description: |
        You can remove a single candidate from the sorting.
      operationId: deleteSortingCandidate
      security:
        - Scopes:
            - "update:sortings"
            - "delete:sorting_association_candidates"
  # Talent Pool
  /pools:
    get:
      tags:
        - Pools
      summary: Get Pools
      description: |
        Returns a list of pools that the requesting user is permitted to view.
      operationId: getPools
      security:
        - Scopes:
            - "read:pools"
    post:
      tags:
        - Pools
      summary: Create Pool
      description: |
        Create a pool.
      operationId: createPool
      security:
        - Scopes:
            - "create:pools"
  /pools/{pool_id}:
    get:
      tags:
        - Pools
      summary: Get Pool
      description: |
        Retrieve a single pool details.
      operationId: getPool
      security:
        - Scopes:
            - "read:pools"
    put:
      tags:
        - Pools
      summary: Update Pool
      description: |
        You can update fields of a pool after the pool is created. The following fields can be updated any time after the pool is created.

        **Available fields to update:**
          - name
          - description
          - metadata
          - app_metadata
      operationId: updatePool
      security:
        - Scopes:
            - "update:pools"
    patch:
      tags:
        - Pools
      summary: Patch Pool
      description: |
        Updates one or more fields in a pool. The operation updates passed fields only.

        **Available fields to update:**
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchPool
      security:
        - Scopes:
            - "update:pools"
    delete:
      tags:
        - Pools
      summary: Delete Pool
      description: |
        Deleting a pool.
      operationId: deletePool
      security:
        - Scopes:
            - "delete:pools"
  /pools/{pool_id}/duplicate:
    post:
      tags:
        - Pools
      summary: Duplicate Pool
      description: |
        Duplicate a pool.
      operationId: duplicatePool
      security:
        - Scopes:
            - "read:pools"
            - "create:pools"
  /pools/{pool_id}/members:
    get:
      tags:
        - Pool Members
      summary: Get Members
      description: |
        Returns a list of members of the pool that the requester is permitted to view.
      operationId: getPoolMembers
      security:
        - Scopes:
            - "read:pools"
            - "read:pool_members"
    post:
      tags:
        - Pool Members
      summary: Add Members
      description: |
        Add Members to the pool.
      operationId: createPoolMembers
      security:
        - Scopes:
            - "update:pools"
            - "create:pool_members"
    delete:
      tags:
        - Pool Members
      summary: Remove Members
      description: |
        You can remove one and more members from a pool with this operation.
      operationId: deletePoolMembers
      security:
        - Scopes:
            - "update:pools"
            - "delete:pool_members"
  /pools/{pool_id}/members/{user_id}:
    get:
      tags:
        - Pool Members
      summary: Get Member
      description: |
        Retrieve single member details from the pool.
      operationId: getPoolMember
      security:
        - Scopes:
            - "read:pools"
            - "read:pool_members"
    delete:
      tags:
        - Pool Members
      summary: Remove Member
      description: |
        You can remove a single member from a pool with this operation. 

        This only removes the specified member from the pool and does not affect their user profile.
      operationId: deletePoolMember
      security:
        - Scopes:
            - "update:pools"
            - "delete:pool_members"
  /pools/{pool_id}/candidates:
    get:
      tags:
        - Pool Candidates
      summary: Get Candidates
      description: |
        Returns a list of candidates of the pool.
      operationId: getPoolCandidates
      security:
        - Scopes:
            - "read:pools"
            - "read:pool_candidates"
    post:
      tags:
        - Pool Candidates
      summary: Add Candidate
      description: |
        Add a candidate.
      operationId: createPoolCandidate
      security:
        - Scopes:
            - "update:pools"
            - "create:pool_candidates"
  /pools/{pool_id}/candidates/{candidate_id}:
    get:
      tags:
        - Pool Candidates
      summary: Get Candidate
      description: |
        Retrieve a single candidate details.
      operationId: getPoolCandidate
      security:
        - Scopes:
            - "read:pools"
            - "read:pool_candidates"
    put:
      tags:
        - Pool Candidates
      summary: Update Candidate
      description: |
        You can update fields of a candidate after the candidate is created.
      operationId: updatePoolCandidate
      security:
        - Scopes:
            - "update:pools"
            - "update:pool_candidates"
    patch:
      tags:
        - Pool Candidates
      summary: Patch Candidate
      description: |
        Updates one or more fields in a candidate. The operation updates passed fields only.
      operationId: patchPoolCandidate
      security:
        - Scopes:
            - "update:pools"
            - "update:pool_candidates"
    delete:
      tags:
        - Pool Candidates
      summary: Delete Candidate
      description: |
        Delete a candidate.
      operationId: deletePoolCandidate
      security:
        - Scopes:
            - "update:pools"
            - "delete:pool_candidates"
  /pools/{pool_id}/candidates/{candidate_id}/move:
    post:
      tags:
        - Pool Candidates
      summary: Move Candidate
      description: |
        Moves the candidate to another pool.
      operationId: movePoolCandidate
      security:
        - Scopes:
            - "update:candidates"
  /pools/{pool_id}/candidates/{candidate_id}/duplicate:
    post:
      tags:
        - Pool Candidates
      summary: Duplicate Candidate
      description: |
        Copy the candidate to another pool.
      operationId: duplicatePoolCandidate
      security:
        - Scopes:
            - "update:pools"
            - "update:pool_candidates"
            - "create:pool_candidates"
  /pools/{pool_id}/candidates/move:
    post:
      tags:
        - Pool Candidates
      summary: Move Candidates (Bulk Action)
      description: |
        Moves candidates to another pool (Bulk Action).
      operationId: movePoolCandidates
      security:
        - Scopes:
            - "update:pools"
            - "update:pool_candidates"
            - "create:pool_candidates"
  /pools/{pool_id}/candidates/duplicate:
    post:
      tags:
        - Pool Candidates
      summary: Duplicate Candidates (Bulk Action)
      description: |
        Copy candidates to another pool.
      operationId: duplicatePoolCandidates
      security:
        - Scopes:
            - "update:pools"
            - "update:pool_candidates"
            - "create:pool_candidates"
  #
  # LOV APIs
  #
  /lookups:
    get:
      tags:
        - lov-lookups
      summary: Get lookups
      description: "Retrieve filtered list of lookups. "
      operationId: get_lookups
      security:
        - Scopes:
            - "read:lookups"
    post:
      tags:
        - lov-lookups
      summary: Create Lookup
      description: "Create Lookup"
      operationId: create_lookup
      security:
        - Scopes:
            - "create:lookups"
  /lookups/{lookup}:
    get:
      tags:
        - lov-lookups
      summary: Get Lookup
      description: "Retrieve lookup details."
      operationId: get_lookup
      security:
        - Scopes:
            - "read:lookups"
    put:
      tags:
        - lov-lookups
      summary: Update Lookup
      description: Update Lookup
      operationId: update_lookup
      security:
        - Scopes:
            - "update:lookups"
    delete:
      tags:
        - lov-lookups
      summary: Delete Lookup
      description: Delete Lookup
      operationId: delete_lookup
      security:
        - Scopes:
            - "delete:lookups"
  /lookups/{lookup}/change:
    post:
      tags:
        - lov-lookups
      summary: Change Lookup Code
      description: "Change Lookup Code"
      operationId: change_lookup_code
      security:
        - Scopes:
            - "update:lookups"
  /lookups/{lookup}/translations:
    get:
      tags:
        - lov-translations
      summary: Get Lookup Translations
      description: "Retrieve filtered list of lookup translations. "
      operationId: get_lookup_translations
      security:
        - Scopes:
            - "read:lookup_translations"
    post:
      tags:
        - lov-translations
      summary: Create Lookup Translation
      description: "Create Lookup Translation"
      operationId: create_lookup_translation
      security:
        - Scopes:
            - "create:lookup_translations"
  /lookups/{lookup}/translations/{language}:
    get:
      tags:
        - lov-translations
      summary: Get Lookup Translation
      description: "Retrieve lookup translation details."
      operationId: get_lookup_translation
      security:
        - Scopes:
            - "read:lookup_translations"
    put:
      tags:
        - lov-translations
      summary: Update Lookup Translation
      description: Update Lookup Translation
      operationId: update_lookup_translation
      security:
        - Scopes:
            - "update:lookup_translations"
    delete:
      tags:
        - lov-translations
      summary: Delete Lookup Translation
      description: Delete Lookup Translation
      operationId: delete_lookup_translation
      security:
        - Scopes:
            - "delete:lookup_values"
  /lookups/{lookup}/values:
    get:
      tags:
        - lov-lookup-values
      summary: Get Lookup Values
      description: "Retrieve filtered list of lookup values. "
      operationId: get_lookup_values
      security:
        - Scopes:
            - "read:lookup_values"
    post:
      tags:
        - lov-lookup-values
      summary: Create Lookup Value
      description: "Create Lookup Value"
      operationId: create_lookup_value
      security:
        - Scopes:
            - "create:lookup_values"
  /lookups/{lookup}/values/{value}:
    get:
      tags:
        - lov-lookup-values
      summary: Get Lookup Value
      description: "Retrieve lookup value details."
      operationId: get_lookup_value
      security:
        - Scopes:
            - "read:lookup_values"
    put:
      tags:
        - lov-lookup-values
      summary: Update Lookup Value
      description: Update Lookup Value
      operationId: update_lookup_value
      security:
        - Scopes:
            - "update:lookup_values"
    delete:
      tags:
        - lov-lookup-values
      summary: Delete Lookup Value
      description: Delete Lookup Value
      operationId: delete_lookup_value
      security:
        - Scopes:
            - "delete:lookup_values"
  /lookups/{lookup}/values/{value}/change:
    post:
      tags:
        - lov-lookup-values
      summary: Change Lookup Value
      description: "Change Lookup Value"
      operationId: change_lookup_value
      security:
        - Scopes:
            - "update:lookup_values"
  /lookups/{lookup}/values/{value}/translations:
    get:
      tags:
        - lov-translations
      summary: Get Lookup Value Translations
      description: "Retrieve filtered list of lookup value translations. "
      operationId: get_lookup_value_translations
      security:
        - Scopes:
            - "read:lookup_value_translations"
    post:
      tags:
        - lov-translations
      summary: Create Lookup Value Translation
      description: "Create Lookup Value Translation"
      operationId: create_lookup_value_translation
      security:
        - Scopes:
            - "create:lookup_value_translations"
  /lookups/{lookup}/values/{value}/translations/{language}:
    get:
      tags:
        - lov-translations
      summary: Get Lookup Value Translation
      description: "Retrieve lookup value translation details."
      operationId: get_lookup_value_translation
      security:
        - Scopes:
            - "read:lookup_value_translations"
    put:
      tags:
        - Translations
      summary: Update Lookup Value Translation
      description: Update Lookup Value Translation
      operationId: update_lookup_value_translation
      security:
        - Scopes:
            - "update:lookup_value_translations"
    delete:
      tags:
        - Translations
      summary: Delete Lookup Value Translation
      description: Delete Lookup Value Translation
      operationId: delete_lookup_value_translation
      security:
        - Scopes:
            - "delete:lookup_value_translations"
  # Profile APIs
  /rating_scales:
    get:
      tags:
        - profile-rating-scales
      summary: Get Scales
      description: |
        Returns a list of scales that the requesting user is permitted to view.
      operationId: getRatingScales
      security:
        - Scopes:
            - "read:scales"
    post:
      tags:
        - profile-rating-scales
      summary: Create Scale
      description: |
        Create a rating scale.
      operationId: createRatingScale
      security:
        - Scopes:
            - "create:scales"
  /rating_scales/{rating_scale_id}:
    get:
      tags:
        - profile-rating-scales
      summary: Get Scale
      description: |
        Retrieve a single rating scale details.
      operationId: getRatingScale
      security:
        - Scopes:
            - "read:scales"
    put:
      tags:
        - profile-rating-scales
      summary: Update Scale
      description: |
        You can update fields of a rating scale after the rating scale is created. The following fields can be updated any time after the rating scale is created.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateRatingScale
      security:
        - Scopes:
            - "update:scales"
    patch:
      tags:
        - profile-rating-scales
      summary: Patch Scale
      description: |
        Updates one or more fields in a rating scale. The operation updates passed fields only.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchRatingScale
      security:
        - Scopes:
            - "update:scales"
    delete:
      tags:
        - profile-rating-scales
      summary: Delete Scale
      description: |
        Delete a Rating Scale.
      operationId: deleteRatingScale
      security:
        - Scopes:
            - "delete:scales"
  /rating_scales/{rating_scale_id}/levels:
    get:
      tags:
        - profile-rating-scale-levels
      summary: Get Levels
      description: |
        Returns a list of levels of the rating scale that the requesting user is permitted to view.
      operationId: getRatingScaleLevels
      security:
        - Scopes:
            - "read:scales"
            - "read:scale_levels"
    post:
      tags:
        - profile-rating-scale-levels
      summary: Create Level
      description: |
        Create a level to the rating scale.
      operationId: createRatingScaleLevel
      security:
        - Scopes:
            - "update:scales"
            - "create:scale_levels"
  /rating_scales/{rating_scale_id}/levels/{level_id}:
    get:
      tags:
        - profile-rating-scale-levels
      summary: Get Level
      description: |
        Retrieve a single level of the rating scale.
      operationId: getRatingScaleLevel
      security:
        - Scopes:
            - "read:scales"
            - "read:scale_levels"
    put:
      tags:
        - profile-rating-scale-levels
      summary: Update Level
      description: |
        You can update fields of a level of the rating scale after the level is created. The following fields can be updated any time after the level is created.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateRatingScaleLevel
      security:
        - Scopes:
            - "update:scales"
            - "update:scale_levels"
    patch:
      tags:
        - profile-rating-scale-levels
      summary: Patch Level
      description: |
        Updates one or more fields in a level of the rating scale. The operation updates passed fields only.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchRatingScaleLevel
      security:
        - Scopes:
            - "update:scales"
            - "update:scale_leves"
    delete:
      tags:
        - profile-rating-scale-levels
      summary: Delete Level
      description: |
        Delete a level from the rating scale.
      operationId: deleteRatingScaleLevel
      security:
        - Scopes:
            - "update:scales"
            - "delete:scale_levels"
  /profile_types:
    get:
      tags:
        - profile-profile-types
      summary: Get Types
      description: |
        Returns a list of types that the requesting user is permitted to view.
      operationId: getProfileTypes
      security:
        - Scopes:
            - "read:profile_types"
    post:
      tags:
        - profile-profile-types
      summary: Create Type
      description: |
        Create a profile type.
      operationId: createProfileType
      security:
        - Scopes:
            - "create:profile_types"
  /profile_types/{profile_type_id}:
    get:
      tags:
        - profile-profile-types
      summary: Get Type
      description: |
        Retrieve a single profile type details.
      operationId: getProfileType
      security:
        - Scopes:
            - "read:profile_types"
    put:
      tags:
        - profile-profile-types
      summary: Update Type
      description: |
        You can update fields of a profile type after the profile type is created. The following fields can be updated any time after the profile type is created.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateProfileType
      security:
        - Scopes:
            - "update:profile_types"
    patch:
      tags:
        - profile-profile-types
      summary: Patch Type
      description: |
        Updates one or more fields in a profile type. The operation updates passed fields only.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchType
      security:
        - Scopes:
            - "update:profile_types"
    delete:
      tags:
        - profile-profile-types
      summary: Delete Type
      description: |
        Delete a profile type.
      operationId: deleteProfileType
      security:
        - Scopes:
            - "delete:profile_types"
  /profile_types/{profile_type_id}/attributes:
    get:
      tags:
        - profile-profile-type-attributes
      summary: Get Attributes
      description: |
        Returns a list of attributes of the profile type that the requesting user is permitted to view.
      operationId: getProfileTypeAttributes
      security:
        - Scopes:
            - "read:profile_types"
            - "read:profile_type_attributes"
    post:
      tags:
        - profile-profile-type-attributes
      summary: Create Attribute
      description: |
        Create an attribute to the profile type.
      operationId: createProfileTypeAttribute
      security:
        - Scopes:
            - "update:profile_types"
            - "create:profile_type_attributes"
  /profile_types/{profile_type_id}/attributes/{attribute_id}:
    get:
      tags:
        - profile-profile-type-attributes
      summary: Get Attribute
      description: |
        Retrieve a single attribute of profile type.
      operationId: getProfileTypeAttribute
      security:
        - Scopes:
            - "read:profile_types"
            - "read:profile_type_attributes"
    put:
      tags:
        - profile-profile-type-attributes
      summary: Update Attribute
      description: |
        You can update fields of an attribute of profile type after the attribute is created. The following fields can be updated any time after the attribute is created.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateProfileTypeAttribute
      security:
        - Scopes:
            - "update:profile_types"
            - "update:profile_type_attributes"
    patch:
      tags:
        - profile-profile-type-attributes
      summary: Patch Attribute
      description: |
        Updates one or more fields in an attribute of profile type. The operation updates passed fields only.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchProfileTypeAttribute
      security:
        - Scopes:
            - "update:profile_types"
            - "update:profile_type_attributes"
    delete:
      tags:
        - profile-profile-type-attributes
      summary: Delete Attribute
      description: |
        Delete an attribute from the profile type.
      operationId: deleteProfileTypeAttribute
      security:
        - Scopes:
            - "update:profile_types"
            - "delete:profile_type_attributes"
  /profile_types/{profile_type_id}/content_types:
    get:
      tags:
        - profile-content-types
      summary: Get Content Types
      description: |
        Returns a list of content types of the profile type that the requesting user is permitted to view.
      operationId: getContentTypes
      security:
        - Scopes:
            - "read:content_types"
    post:
      tags:
        - profile-content-types
      summary: Create Content Type
      description: |
        Create a content type to the profile type.
      operationId: createContentType
      security:
        - Scopes:
            - "create:content_types"
  /profile_types/{profile_type_id}/content_types/{content_type_id}:
    get:
      tags:
        - profile-content-types
      summary: Get Content Type
      description: |
        Retrieve a single content type of the profile type.
      operationId: getContentType
      security:
        - Scopes:
            - "read:content_types"
    put:
      tags:
        - profile-content-types
      summary: Update Content Type
      description: |
        You can update fields of a content type of profile type after the content type is created. The following fields can be updated any time after the content type is created.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateContentType
      security:
        - Scopes:
            - "update:profile_types"
            - "update:content_types"
    patch:
      tags:
        - profile-content-types
      summary: Patch Content Type
      description: |
        Updates one or more fields in a content type of profile type. The operation updates passed fields only.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchContentType
      security:
        - Scopes:
            - "update:content_types"
    delete:
      tags:
        - profile-content-types
      summary: Delete Content Type
      description: |
        Delete a content type from the profile type.
      operationId: deleteContentType
      security:
        - Scopes:
            - "update:profile_types"
            - "delete:content_types"
  /profile_types/{profile_type_id}/content_types/{content_type_id}/attributes:
    get:
      tags:
        - profile-content-type-attributes
      summary: Get Attributes
      description: |
        Returns a list of attributes of the content type that the requesting user is permitted to view.
      operationId: getContentTypeAttributes
      security:
        - Scopes:
            - "read:content_types"
            - "read:content_type_attributes"
    post:
      tags:
        - profile-content-type-attributes
      summary: Create Attribute
      description: |
        Create an attribute to the content type.
      operationId: createContentTypeAttribute
      security:
        - Scopes:
            - "update:content_types"
            - "create:content_type_attributes"
  /profile_types/{profile_type_id}/content_types/{content_type_id}/attributes/{attribute_id}:
    get:
      tags:
        - profile-content-type-attributes
      summary: Get Attribute
      description: |
        Retrieve a single attribute of content type.
      operationId: getContentTypeAttribute
      security:
        - Scopes:
            - "read:content_types"
            - "read:content_type_attributes"
    put:
      tags:
        - profile-content-type-attributes
      summary: Update Attribute
      description: |
        You can update fields of an attribute of content type after the attribute is created. The following fields can be updated any time after the attribute is created.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: updateContentTypeAttribute
      security:
        - Scopes:
            - "update:content_types"
            - "update:content_type_attributes"
    patch:
      tags:
        - profile-content-type-attributes
      summary: Patch Attribute
      description: |
        Updates one or more fields in an attribute of content type. The operation updates passed fields only.

        **Available fields to update:**
          - id
          - name
          - description
          - metadata
          - app_metadata
      operationId: patchContentTypeAttribute
      security:
        - Scopes:
            - "update:content_types"
            - "update:content_type_attributes"
    delete:
      tags:
        - profile-content-type-attributes
      summary: Delete Attribute
      description: |
        Delete an attribute from the content type.
      operationId: deleteContentTypeAttribute
      security:
        - Scopes:
            - "update:content_types"
            - "delete:content_type_attributes"
  /profiles:
    get:
      tags:
        - profile-profiles
      summary: Get Profiles
      description: |
        Returns a list of profiles that the requesting user is permitted to view.
      operationId: getProfiles
      security:
        - Scopes:
            - "read:profiles"
    post:
      tags:
        - profile-profiles
      summary: Create Profile
      description: |
        Create a profile.
      operationId: createProfile
      security:
        - Scopes:
            - "create:profiles"
  /profiles/{profile_id}:
    get:
      tags:
        - profile-profiles
      summary: Get Profile
      description: |
        Retrieve a single profile details.
      operationId: getProfile
      security:
        - Scopes:
            - "read:profiles"
    put:
      tags:
        - profile-profiles
      summary: Update Profile
      description: |
        You can update fields of a profile after the profile is created. The following fields can be updated any time after the profile is created.

        **Available fields to update:**
          - name
          - description
          - profile_metadata
          - app_metadata
      operationId: updateProfile
      security:
        - Scopes:
            - "update:profiles"
    patch:
      tags:
        - profile-profiles
      summary: Patch Profile
      description: |
        Updates one or more fields in a profile. The operation updates passed fields only.

        **Available fields to update:**
          - name
          - description
          - profile_metadata
          - app_metadata
      operationId: patchProfile
      security:
        - Scopes:
            - "update:profiles"
    delete:
      tags:
        - profile-profiles
      summary: Delete Profile
      description: |
        Delete a profile.
      operationId: deleteProfile
      security:
        - Scopes:
            - "delete:profiles"
  /profiles/{profile_id}/override:
    post:
      tags:
        - profile-profiles
      summary: Override Profile
      description: |
        Merges a profile's profile. Copies data of the profile specified in the request body and overrides to the profile specified in the resource URL. 

        You must passed following data in the request body:
          - **Profile Id** - Required, The profile to be copied.
          - **Allow Null Values** - Default is `false`. If true, system override the profile specified in the resource URL with the profile specified in the request body without checking NULL value. Otherwise, system override the profile specified in the resource URL with the data is not empty only.
          - **Options** - Optional, System will override only passed data of the profile when options have provided. Otherwise, system will override all data of the profile to the candidata profile specified in the resource URL.
            
            **Available options:**
            - **Profile** - Only profile main data like name, description, ...etc.
            - **Names** - Only names of the profile specified in the request body.
            - **Images** - Only images of the profile specified in the request body.
            - **Emails** - Only emails of the profile specified in the request body.
            - **Phones** - Only phones of the profile specified in the request body.
            - **Webs** - Only webs of the profile specified in the request body.
            - **Socials** - Only social accounts of the profile specified in the request body.
            - **Addresses** - Only addresses of the profile specified in the request body.
            - **Educations** - Only education entries of the profile specified in the request body.
            - **Languages** - Only languages of the profile specified in the request body.
            - **Skills** - Only skills of the profile specified in the request body.
            - **Experiences** - Only expriences of the profile specified in the request body.
            - **Attachments** - Only attachments of the profile specified in the request body.
      operationId: overrideProfile
      security:
        - Scopes:
            - "update:profiles"
  /profiles/{profile_id}/names:
    get:
      tags:
        - profile-profile-names
      summary: Get Names
      description: |
        Returns a list of names of the profile.
      operationId: getProfileNames
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_names"
    post:
      tags:
        - profile-profile-names
      summary: Add Name
      description: |
        Create a name to the profile.
      operationId: createProfileName
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_names"
  /profiles/{profile_id}/names/{name_id}:
    get:
      tags:
        - profile-profile-names
      summary: Get Name
      description: |
        Retrieve a single name details.
      operationId: getProfileName
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_names"
    put:
      tags:
        - profile-profile-names
      summary: Update Name
      description: |
        You can update fields of a name after the name is created.
      operationId: updateProfileName
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_names"
    patch:
      tags:
        - profile-profile-names
      summary: Patch Name
      description: |
        Updates one or more fields in a name. The operation updates passed fields only.
      operationId: patchProfileName
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_names"
    delete:
      tags:
        - profile-profile-names
      summary: Delete Name
      description: |
        Delete a name from the profile.
      operationId: deleteProfileName
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_names"
  /profiles/{profile_id}/images:
    get:
      tags:
        - profile-profile-images
      summary: Get Images
      description: |
        Returns a list of images of the profile.
      operationId: getProfileImages
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_images"
    post:
      tags:
        - profile-profile-images
      summary: Add Image
      description: |
        Create an image to the profile.
      operationId: createProfileImage
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_images"
  /profiles/{profile_id}/images/{image_id}:
    get:
      tags:
        - profile-profile-images
      summary: Get Image
      description: |
        Retrieve a single image details.
      operationId: getProfileImage
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_images"
    put:
      tags:
        - profile-profile-images
      summary: Update Image
      description: |
        You can update fields of an image after the image is created.
      operationId: updateProfileImage
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_images"
    patch:
      tags:
        - profile-profile-images
      summary: Patch Image
      description: |
        Updates one or more fields in an image. The operation updates passed fields only.
      operationId: patchProfileImage
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_images"
    delete:
      tags:
        - profile-profile-images
      summary: Delete Image
      description: |
        Delete an image from the profile.
      operationId: deleteProfileImage
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_images"
  /profiles/{profile_id}/emails:
    get:
      tags:
        - profile-profile-emails
      summary: Get Emails
      description: |
        Returns a list of emails of the profile.
      operationId: getProfileEmails
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_emails"
    post:
      tags:
        - profile-profile-emails
      summary: Add Email
      description: |
        Create an email to the profile.
      operationId: createProfileEmail
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_emails"
  /profiles/{profile_id}/emails/{email_id}:
    get:
      tags:
        - profile-profile-emails
      summary: Get Email
      description: |
        Retrieve a single email details.
      operationId: getProfileEmail
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_emails"
    put:
      tags:
        - profile-profile-emails
      summary: Update Email
      description: |
        You can update fields of an email after the email is created.
      operationId: updateProfileEmail
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_emails"
    patch:
      tags:
        - profile-profile-emails
      summary: Patch Email
      description: |
        Updates one or more fields in an email. The operation updates passed fields only.
      operationId: patchProfileEmail
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_emails"
    delete:
      tags:
        - profile-profile-emails
      summary: Delete Email
      description: |
        Delete an email from the profile.
      operationId: deleteProfileEmail
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_emails"
  /profiles/{profile_id}/phones:
    get:
      tags:
        - profile-profile-phones
      summary: Get Phones
      description: |
        Returns a list of phones of the profile.
      operationId: getProfilePhones
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_phones"
    post:
      tags:
        - profile-profile-phones
      summary: Add Phone
      description: |
        Create a phone to the profile.
      operationId: createProfilePhone
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_phones"
  /profiles/{profile_id}/phones/{phone_id}:
    get:
      tags:
        - profile-profile-phones
      summary: Get Phone
      description: |
        Retrieve a single phone details.
      operationId: getProfilePhone
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_phones"
    put:
      tags:
        - profile-profile-phones
      summary: Update Phone
      description: |
        You can update fields of a phone after the phone is created.
      operationId: updateProfilePhone
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_phones"
    patch:
      tags:
        - profile-profile-phones
      summary: Patch Phone
      description: |
        Updates one or more fields in a phone. The operation updates passed fields only.
      operationId: patchProfilePhone
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_phones"
    delete:
      tags:
        - profile-profile-phones
      summary: Delete Phone
      description: |
        Delete a phone from the profile.
      operationId: deleteProfilePhone
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_phones"
  /profiles/{profile_id}/webs:
    get:
      tags:
        - profile-profile-webs
      summary: Get Webs
      description: |
        Returns a list of webs of the profile.
      operationId: getProfileWebs
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_webs"
    post:
      tags:
        - profile-profile-webs
      summary: Add Web
      description: |
        Create a web to the profile.
      operationId: createProfileWeb
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_webs"
  /profiles/{profile_id}/webs/{web_id}:
    get:
      tags:
        - profile-profile-webs
      summary: Get Web
      description: |
        Retrieve a single web details.
      operationId: getProfileWeb
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_webs"
    put:
      tags:
        - profile-profile-webs
      summary: Update Web
      description: |
        You can update fields of a web after the web is created.
      operationId: updateProfileWeb
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_webs"
    patch:
      tags:
        - profile-profile-webs
      summary: Patch Web
      description: |
        Updates one or more fields in a web. The operation updates passed fields only.
      operationId: patchProfileWeb
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_webs"
    delete:
      tags:
        - profile-profile-webs
      summary: Delete Web
      description: |
        Delete a web from the profile.
      operationId: deleteProfileWeb
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_webs"
  /profiles/{profile_id}/socials:
    get:
      tags:
        - profile-profile-socials
      summary: Get Socials
      description: |
        Returns a list of socials of the profile.
      operationId: getProfileSocials
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_socials"
    post:
      tags:
        - profile-profile-socials
      summary: Add Social
      description: |
        Create a social to the profile.
      operationId: createProfileSocial
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_socials"
  /profiles/{profile_id}/socials/{social_id}:
    get:
      tags:
        - profile-profile-socials
      summary: Get Social
      description: |
        Retrieve a single social details.
      operationId: getProfileSocial
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_socials"
    put:
      tags:
        - profile-profile-socials
      summary: Update Social
      description: |
        You can update fields of a social after the social is created.
      operationId: updateProfileSocial
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_socials"
    patch:
      tags:
        - profile-profile-socials
      summary: Patch Social
      description: |
        Updates one or more fields in a social. The operation updates passed fields only.
      operationId: patchProfileSocial
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_socials"
    delete:
      tags:
        - profile-profile-socials
      summary: Delete Social
      description: |
        Delete a social from the profile.
      operationId: deleteProfileSocial
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_socials"
  /profiles/{profile_id}/addresses:
    get:
      tags:
        - profile-profile-addresses
      summary: Get Addresses
      description: |
        Returns a list of addresses of the profile.
      operationId: getProfileAddresses
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_addresses"
    post:
      tags:
        - profile-profile-addresses
      summary: Add Address
      description: |
        Create an address to the profile.
      operationId: createProfileAddress
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_addresses"
  /profiles/{profile_id}/addresses/{address_id}:
    get:
      tags:
        - profile-profile-addresses
      summary: Get Address
      description: |
        Retrieve a single address details.
      operationId: getProfileAddress
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_addresses"
    put:
      tags:
        - profile-profile-addresses
      summary: Update Address
      description: |
        You can update fields of an address after the address is created.
      operationId: updateProfileAddress
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_addresses"
    patch:
      tags:
        - profile-profile-addresses
      summary: Patch Address
      description: |
        Updates one or more fields in an address. The operation updates passed fields only.
      operationId: patchProfileAddress
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_addresses"
    delete:
      tags:
        - profile-profile-addresses
      summary: Delete Address
      description: |
        Delete an address from the profile.
      operationId: deleteProfileAddress
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_addresses"
  /profiles/{profile_id}/educations:
    get:
      tags:
        - profile-profile-educations
      summary: Get Educations
      description: |
        Returns a list of educations of the profile.
      operationId: getProfileEducations
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_educations"
    post:
      tags:
        - profile-profile-educations
      summary: Add Education
      description: |
        Create an education to the profile.
      operationId: createProfileEducation
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_educations"
  /profiles/{profile_id}/educations/{education_id}:
    get:
      tags:
        - profile-profile-educations
      summary: Get Education
      description: |
        Retrieve a single education details.
      operationId: getProfileEducation
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_educations"
    put:
      tags:
        - profile-profile-educations
      summary: Update Education
      description: |
        You can update fields of an education after the education is created.
      operationId: updateProfileEducation
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_educations"
    patch:
      tags:
        - profile-profile-educations
      summary: Patch Education
      description: |
        Updates one or more fields in an education. The operation updates passed fields only.
      operationId: patchProfileEducation
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_educations"
    delete:
      tags:
        - profile-profile-educations
      summary: Delete Education
      description: |
        Delete an education from the profile.
      operationId: deleteProfileEducation
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_educations"
  /profiles/{profile_id}/languages:
    get:
      tags:
        - profile-profile-languages
      summary: Get Languages
      description: |
        Returns a list of languages of the profile.
      operationId: getProfileLanguages
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_languages"
    post:
      tags:
        - profile-profile-languages
      summary: Add Language
      description: |
        Create a language to the profile.
      operationId: createProfileLanguage
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_languages"
  /profiles/{profile_id}/languages/{language_id}:
    get:
      tags:
        - profile-profile-languages
      summary: Get Language
      description: |
        Retrieve a single language details.
      operationId: getProfileLanguage
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_languages"
    put:
      tags:
        - profile-profile-languages
      summary: Update Language
      description: |
        You can update fields of a language after the language is created.
      operationId: updateProfileLanguage
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_languages"
    patch:
      tags:
        - profile-profile-languages
      summary: Patch Language
      description: |
        Updates one or more fields in a language. The operation updates passed fields only.
      operationId: patchProfileLanguage
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_languages"
    delete:
      tags:
        - profile-profile-languages
      summary: Delete Language
      description: |
        Delete a language from the profile.
      operationId: deleteProfileLanguage
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_languages"
  /profiles/{profile_id}/experiences:
    get:
      tags:
        - profile-profile-experiences
      summary: Get Experiences
      description: |
        Returns a list of experiences of the profile.
      operationId: getProfileExperiences
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_experiences"
    post:
      tags:
        - profile-profile-experiences
      summary: Add Experience
      description: |
        Create an experience to the profile.
      operationId: createProfileExperience
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_experiences"
  /profiles/{profile_id}/experiences/{experience_id}:
    get:
      tags:
        - profile-profile-experiences
      summary: Get Experience
      description: |
        Retrieve a single experience details.
      operationId: getProfileExperience
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_experiences"
    put:
      tags:
        - profile-profile-experiences
      summary: Update Experience
      description: |
        You can update fields of an experience after the experience is created.
      operationId: updateProfileExperience
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_experiences"
    patch:
      tags:
        - profile-profile-experiences
      summary: Patch Experience
      description: |
        Updates one or more fields in an experience. The operation updates passed fields only.
      operationId: patchProfileExperience
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_experiences"
    delete:
      tags:
        - profile-profile-experiences
      summary: Delete Experience
      description: |
        Delete an experience from the profile.
      operationId: deleteProfileExperience
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_experiences"
  /profiles/{profile_id}/skills:
    get:
      tags:
        - profile-profile-skills
      summary: Get Skills
      description: |
        Returns a list of skills of the profile.
      operationId: getProfileSkills
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_skills"
    post:
      tags:
        - profile-profile-skills
      summary: Add Skill
      description: |
        Create a skill to the profile.
      operationId: createProfileSkill
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_skills"
  /profiles/{profile_id}/skills/{skill_id}:
    get:
      tags:
        - profile-profile-skills
      summary: Get Skill
      description: |
        Retrieve a single skill details.
      operationId: getProfileSkill
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_skills"
    put:
      tags:
        - profile-profile-skills
      summary: Update Skill
      description: |
        You can update fields of a skill after the skill is created.
      operationId: updateProfileSkill
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_skills"
    patch:
      tags:
        - profile-profile-skills
      summary: Patch Skill
      description: |
        Updates one or more fields in a skill. The operation updates passed fields only.
      operationId: patchProfileSkill
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_skills"
    delete:
      tags:
        - profile-profile-skills
      summary: Delete Skill
      description: |
        Delete a skill from the profile.
      operationId: deleteProfileSkill
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_skills"
  /profiles/{profile_id}/attachments:
    get:
      tags:
        - profile-profile-attachments
      summary: Get Attachments
      description: |
        Returns a list of attachments of the profile.
      operationId: getProfileAttachments
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_attachments"
    post:
      tags:
        - profile-profile-attachments
      summary: Add Attachment
      description: |
        Create an attachment to the profile.
      operationId: createProfileAttachment
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_attachments"
  /profiles/{profile_id}/attachments/{attachment_id}:
    get:
      tags:
        - profile-profile-attachments
      summary: Get Attachment
      description: |
        Retrieve a single attachment details.
      operationId: getProfileAttachment
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_attachments"
    put:
      tags:
        - profile-profile-attachments
      summary: Update Attachment
      description: |
        You can update fields of an attachment after the attachment is created.
      operationId: updateProfileAttachment
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_attachments"
    patch:
      tags:
        - profile-profile-attachments
      summary: Patch Attachment
      description: |
        Updates one or more fields in an attachment. The operation updates passed fields only.
      operationId: patchProfileAttachment
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_attachments"
    delete:
      tags:
        - profile-profile-attachments
      summary: Delete Attachment
      description: |
        Delete an attachment from the profile.
      operationId: deleteProfileAttachment
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_attachments"
  /profiles/{profile_id}/{content_type_id}:
    get:
      tags:
        - profile-profile-contents
      summary: Get Contents
      description: |
        Returns a list of contents of the profile.
      operationId: getProfileContents
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_contents"
    post:
      tags:
        - profile-profile-contents
      summary: Add Contents
      description: |
        Create contents to the profile.
      operationId: createProfileContents
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_contents"
  /profiles/{profile_id}/{content_type_id}/{content_id}:
    get:
      tags:
        - profile-profile-contents
      summary: Get Content
      description: |
        Retrieve a single content details.
      operationId: getProfileContent
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_contents"
    put:
      tags:
        - profile-profile-contents
      summary: Update Content
      description: |
        You can update fields of a content after the content is created.
      operationId: updateProfileContent
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_attachments"
    patch:
      tags:
        - profile-profile-contents
      summary: Patch Contents
      description: |
        Updates one or more fields in a content. The operation updates passed fields only.
      operationId: patchProfileContent
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_contents"
    delete:
      tags:
        - profile-profile-contents
      summary: Delete Content
      description: |
        Delete a content from the profile.
      operationId: deleteProfileContent
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_contents"
  /profiles/{profile_id}/citizenships:
    get:
      tags:
        - profile-profile-citizenships
      summary: Get Citizenships
      description: |
        Returns a list of citizenships of the profile.
      operationId: getProfileCitizenships
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_citizenships"
    post:
      tags:
        - profile-profile-citizenships
      summary: Add Citizenship
      description: |
        Create a citizenship to the profile.
      operationId: createProfileCitizenship
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_citizenships"
  /profiles/{profile_id}/citizenships/{citizenship_id}:
    get:
      tags:
        - profile-profile-citizenships
      summary: Get Citizenship
      description: |
        Retrieve a single citizenship details.
      operationId: getProfileCitizenship
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_citizenships"
    put:
      tags:
        - profile-profile-citizenships
      summary: Update Citizenship
      description: |
        You can update fields of a citizenship after the test is created.
      operationId: updateProfileCitizenship
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_citizenships"
    patch:
      tags:
        - profile-profile-citizenships
      summary: Patch Citizenship
      description: |
        Updates one or more fields in a citizenship. The operation updates passed fields only.
      operationId: patchProfileCitizenship
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_citizenships"
    delete:
      tags:
        - profile-profile-citizenships
      summary: Delete Citizenship
      description: |
        Delete a citizenship from the profile.
      operationId: deleteProfileCitizenship
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_citizenships"
  /profiles/{profile_id}/tests:
    get:
      tags:
        - profile-profile-tests
      summary: Get Tests
      description: |
        Returns a list of tests of the profile.
      operationId: getProfileTests
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_tests"
    post:
      tags:
        - profile-profile-tests
      summary: Add Test
      description: |
        Create a test to the profile.
      operationId: createProfileTest
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_tests"
  /profiles/{profile_id}/tests/{test_id}:
    get:
      tags:
        - profile-profile-tests
      summary: Get Test
      description: |
        Retrieve a single test details.
      operationId: getProfileTest
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_tests"
    put:
      tags:
        - profile-profile-tests
      summary: Update Test
      description: |
        You can update fields of a test after the test is created.
      operationId: updateProfileTest
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_tests"
    patch:
      tags:
        - profile-profile-tests
      summary: Patch Test
      description: |
        Updates one or more fields in a test. The operation updates passed fields only.
      operationId: patchProfileTest
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_tests"
    delete:
      tags:
        - profile-profile-tests
      summary: Delete Test
      description: |
        Delete a test from the profile.
      operationId: deleteProfileTest
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_tests"
  /profiles/{profile_id}/tests/{test_id}/components:
    get:
      tags:
        - profile-profile-test-components
      summary: Get Test Components
      description: |
        Returns a list of components of the test.
      operationId: getProfileTestComponents
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_tests"
    post:
      tags:
        - profile-profile-test-components
      summary: Add Test Component
      description: |
        Create a component to the test.
      operationId: createProfileTestComponent
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_tests"
  /profiles/{profile_id}/tests/{test_id}/components/{component_id}:
    get:
      tags:
        - profile-profile-test-components
      summary: Get Test Component
      description: |
        Retrieve a single test component details.
      operationId: getProfileTestComponent
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_tests"
    put:
      tags:
        - profile-profile-test-components
      summary: Update Test Component
      description: |
        You can update fields of a component after the component is created.
      operationId: updateProfileTestComponent
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_tests"
    patch:
      tags:
        - profile-profile-test-components
      summary: Patch Test Component
      description: |
        Updates one or more fields in a component. The operation updates passed fields only.
      operationId: patchProfileTestComponent
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_tests"
    delete:
      tags:
        - profile-profile-test-components
      summary: Delete Test Component
      description: |
        Delete a component from the test.
      operationId: deleteProfileTestComponent
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_tests"
  /profiles/{profile_id}/awards:
    get:
      tags:
        - profile-profile-awards
      summary: Get Awards
      description: |
        Returns a list of awards of the profile.
      operationId: getProfileAwards
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_awards"
    post:
      tags:
        - profile-profile-awards
      summary: Add Award
      description: |
        Create an award to the profile.
      operationId: createProfileAward
      security:
        - Scopes:
            - "update:profiles"
            - "create:profile_awards"
  /profiles/{profile_id}/awards/{award_id}:
    get:
      tags:
        - profile-profile-awards
      summary: Get Award
      description: |
        Retrieve a single award details.
      operationId: getProfileAward
      security:
        - Scopes:
            - "read:profiles"
            - "read:profile_awards"
    put:
      tags:
        - profile-profile-awards
      summary: Update Award
      description: |
        You can update fields of an award after the award is created.
      operationId: updateProfileAward
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_awards"
    patch:
      tags:
        - profile-profile-awards
      summary: Patch Award
      description: |
        Updates one or more fields in an award. The operation updates passed fields only.
      operationId: patchProfileAward
      security:
        - Scopes:
            - "update:profiles"
            - "update:profile_awards"
    delete:
      tags:
        - profile-profile-awards
      summary: Delete Award
      description: |
        Delete an award from the profile.
      operationId: deleteProfileAward
      security:
        - Scopes:
            - "update:profiles"
            - "delete:profile_awards"
components:
  securitySchemes:
    basic_auth:
      description: Basic Authentication
      type: http
      scheme: basic
    bearer_auth:
      description: Bearer Authentication
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      type: apiKey
      description: >
        For this sample, you can use the api key `special-key` to test the
        authorization filters.
      in: header
      name: X-API-KEY
    Scopes:
      description: |
        Get access to data while protecting your account credentials.
        OAuth2 is also a safer and more secure way to give you access.

        [See more](https://developer.reworkly.com/docs/server)
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "/authorize"
          scopes: {}
    open_id_connect:
      type: openIdConnect
      openIdConnectUrl: https://{subdomain}/server/{version}/.well-known/openid-configuration
    cookie_auth:
      type: apiKey
      in: cookie
      name: JSESSIONID
